language: generic
sudo: false

env:
  global:
    BYOND_MAJOR="510"
    BYOND_MINOR="1345"
    NODE_VERSION="4"

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386 
      - libgcc1:i386
      - libstdc++6:i386

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $NODE_VERSION
  - npm install -g gulp-cli
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q
  
before_script:
  - cd tgui && npm install && cd ..
  - chmod +x ./tools/Travis/install-byond.sh
  - ./tools/Travis/install-byond.sh

script:
  - shopt -s globstar
  - (! grep 'step_[xy]' maps/**/*.dmm)
  - (! find nano/templates/ -type f -exec md5sum {} + | sort | uniq -D -w 32 | grep nano)
  - (! grep -En "<\s*span\s+class\s*=\s*('[^'>]+|[^'>]+')\s*>" **/*.dm)
  - awk -f tools/travis/indentation.awk **/*.dm
  - md5sum -c - <<< "663A04D1ED66921DD1077C6BAE17072B *Eternal.int"
  - cd tgui && gulp
  - cd ..
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - DreamMaker Eternal.dme
